change to python3.6
NetKnights-GmbH/centos7 pull request #20
Opened 2021-07-21 09:54 UTC by pablo-knight

related to #15

2021-07-21 10:16 UTC, pablo-knight commented
client has to add epel release repo to get python3_mod_wsgi package from it

yum install epel-release

2021-10-16 14:43 UTC, plettich requested changes

2021-10-16 14:43 UTC, plettich commented on SPECS/privacyidea.spec
> +%if 0%{centos_ver} == 7
we can drop this condition and use `virtualenv-3` on both CentOS7 and 8

2023-02-06 12:40 UTC, plettich approved these changes

2023-02-06 12:40 UTC, merged